apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-{{ .Values.user }}
subjects:
- kind: ServiceAccount
  name: prometheus-{{ .Values.user }}
