user: userX # Replace me

# alertmanager
alertmanager:
  enabled: false

# grafana
grafana:
  enabled: false

# prometheus
prometheus:
  enabled: false

# pushgateway
pushgateway:
  enabled: false

# thanos-ruler
ruler:
  enabled: false

# thanos-query
query:
  enabled: false