user: userX # Replace me

# alertmanager
alertmanager:
  enabled: false

# grafana
grafana:
  datasources:
  - name: prometheus
    access: proxy
    editable: false
    type: prometheus
    url: http://prometheus-operated.user4-monitoring.svc.cluster.local:9090
  enabled: true

# prometheus
prometheus:
  enabled: false

# pushgateway
pushgateway:
  enabled: false

# thanos-ruler
ruler:
  enabled: false

# thanos-query
query:
  enabled: false