{{- define "alertmanager.config-mailcatcher" }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Values.user }}-mailcatcher
  labels:
    alertmanagerConfig: {{ .Values.user }}-alertmanager
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'mailcatcher'
  receivers:
    - name: 'mailcatcher'
      emailConfigs:
        - to: alert@localhost
          from: prometheus-operator@localhost
          smarthost: mailcatcher:1025
          requireTLS: false
{{- end }}