{{- define "query.svc" }}
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app.kubernetes.io/name: thanos-query
spec:
  ports:
  - name: http
    port: 10902
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: thanos-query
  type: ClusterIP
{{- end }}