{{- define "grafana.datasource" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-datasources
  labels:
    app.kubernetes.io/name: grafana
    datasource: "true"
stringData:
  dashboardproviders.yaml: |
    apiVersion: 1
    datasources:
      - name: thanos-querier
        access: proxy
        editable: false
        type: prometheus
        url: http://thanos-query.{{ .Values.user }}-monitoring.svc.cluster.local:10902
        version: 1
{{- end }}