{{- define  "blackboxexporter.deploy" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: quay.io/prometheus/blackbox-exporter:v0.24.0
          args:
            - --config.file=/etc/blackbox_exporter/config.yml
          ports:
            - containerPort: 9115
              name: http
          volumeMounts:
            - mountPath: /etc/blackbox_exporter/
              name: blackbox-config
          resources: {}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: blackbox-config
          configMap:
            defaultMode: 420
            name: blackbox-exporter-config
{{- end }}