{{- define  "blackboxexporter.svc" }}
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: 9115
  selector:
    app.kubernetes.io/name: blackbox-exporter
  type: ClusterIP
{{- end }}
