{{- define "grafana.servicemonitor" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-monitor
spec:
  endpoints:
    - basicAuth:
        password:
          name: basic-auth
          key: {{ .Values.user }}
        username:
          name: basic-auth
          key: grafana_user
      interval: 60s
      port: http
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
{{- end }}