{{- define "ruler.ruler" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  labels:
    app.kubernetes.io/name: thanos-ruler
  name: thanos-ruler
spec:
  image: quay.io/thanos/thanos:v0.28.1
  alertQueryUrl: {{ .Values.user }}-thanos-query.training.cluster.acend.ch
  evaluationInterval: 10s
  queryEndpoints:
  - dnssrv+_http._tcp.thanos-querier.{{ .Values.user }}-monitoring.svc.cluster.local
  ruleSelector: {}
  ruleNamespaceSelector:
    matchLabels:
      user: {{ .Values.user }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thanosruler-alertmanager-config
stringData:
  alertmanager-configs.yaml: |-
    alertmanagers:
    - static_configs:
      - "dnssrv+_web._tcp.alertmanager-operated.{{ .Values.user }}-monitoring.svc.cluster.local"
      api_version: v2```
{{- end }}