{{- define "alertmanager.alertmanager" }}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.user }}-am
  name: {{ .Values.user }}-am
spec: {}
{{- end }}