apiVersion: v1
data:
  admin: JDEkSzNRZUlsOHAkZVZZb1h2RERNWk40b3RJT2tBc3AwLw== # $(openssl passwd -1 admin)
  {{ .Values.user }}: JDEkSzNRZUlsOHAkZVZZb1h2RERNWk40b3RJT2tBc3AwLw== # $(openssl passwd -1 admin)
  grafana_user: {{ .Values.user | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: basic-auth
  name: basic-auth